management:
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh
spring:
  application:
    name: config-client
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
server:
  port: 8881




