spring:
  application:
    name: service-zuul
server:
  port: 8766
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-robin
    api-b:
      path: /api-b/**
      serviceId: service-feign
