spring:
  application:
    name: service-robin
  rabbitmq:
    port: 5672
    host: 119.29.163.100
server:
  port: 8764
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
