spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://127.0.0.1:10086
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
feign:
  hystrix:
   enabled: true
