spring:
  application:
    name: service-hi
  rabbitmq:
    port: 5672
    host: 119.29.163.100
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
